# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleeprecord',
            name='report',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='RR', to='sleep.Report'),
        ),
    ]
