# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180308_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleeprecord',
            name='report',
        ),
    ]
